<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('shippers', function (Blueprint $table) {
            $table->id();
            $table->string('account_number')->unique(); // Auto-generated by the app
            $table->string('shipper_name');
            $table->string('name_commercial')->nullable();
            $table->string('abbreviation')->nullable();
            $table->string('id_registry_commercial')->nullable();
            $table->string('file_register_commercial')->nullable();
            $table->string('registry_id_tax')->nullable();
            $table->string('email')->nullable();
            $table->string('zip')->nullable();
            $table->string('phone1')->nullable();
            $table->string('phone2')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('shippers');
    }
};
